name: shuei_ai_chat
description: "Build a simple AI chat app that allows users to chat with personal assigntant AI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.0
  http: ^1.2.2
  get_it: ^7.7.0
  dio: ^5.6.0
  intl: ^0.19.0
  equatable: ^2.0.5
  fluttertoast: ^8.2.8
  retrofit: ^4.2.0
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.1
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.1
  flutter_native_splash: ^2.4.1
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  chat_bubbles: ^1.6.0
  provider: ^6.1.2
  audioplayers: ^6.1.0
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.2
  build_runner: ^2.4.11
  mockito: ^5.4.4
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/font/
    - assets/animation/
    - .env
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/font/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/font/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/font/SFProDisplay-Semi-Bold.ttf
          weight: 600
        - asset: assets/font/SFProDisplay-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/icon/ic_splash.png"
  image_dark: "assets/icon/ic_dark_splash.png"
  android_12:
    image: "assets/icon/ic_android_splash.png"
    image_dark: "assets/icon/ic_dark_android_splash.png"
    color: "#ffffff"
    color_dark: "#000000"
  android_gravity: fill
  fullscreen: true
  android: true
  ios: true
